---
title		: Biostatistical consulting
subtitle	: 
author		: Steve Lane
framework	: revealjs
revealjs    :
 theme: sky
 transition: cube
 transitionSpeed: fast
 history: false
 width: 1280
 height: 960
 center: "true"
highlighter	: highlight.js
hitheme		: tomorrow
widgets		:
- mathjax
- bootstrap
ext_widgets : {rCharts: [/libraries/nvd3]}
mode		: selfcontained
theme		: sky
url		:
 assets: ../assets
 lib: ../libraries
---

<!-- To compile: -->
<!-- require(slidify) -->
<!-- slidify("filename.rmd") -->
<!-- Post creation need to edit html to adjust height and width. -->

```{r setup,message=FALSE,echo=FALSE,cache=FALSE}
library(reshape2)
library(rCharts)
library(lubridate)
library(plyr)
knitr::opts_chunk$set(comment=NA,results="asis",tidy=FALSE,message=TRUE,echo=FALSE)
```

## Biostatistical consulting
### Steve Lane
##### stephen.lane 'at' barwonhealth.org.au
##### Barwon Health Biostatistics Unit
<!-- Date (if required): -->
<!-- ##### `r format(Sys.time(), "%A %B %d, %Y")` -->

<aside class="notes">

- Kept here as a placeholder

</aside>

---

<section>

<!-- To start downwards slides -->

## Prior to my current role

---

### A wandering path...

- 1999
  - Engineering
- 2003
  - Commerce/Science
- 2004
  - Mathematics
- 2007
  - Honours in statistics
- 2012
  - PhD in statistics

---

### Positions I've held

- 2007
  - ABS (Australian Bureau of Statistics) Cadetship
- 2008
  - Senior Research Officer at ABS
- 2012
  - Research Fellow, Head of Unit (current)

</section>

---

<section>

## Some projects I've worked on

---

### Clinical trials

- Short course vs. long course intravenous therapy for cellulitis
- N-Acetyl-Cysteine as a preventive agent for Post-operative cognitive decline
- What does a biostatistician do?
  - Look at all things 'measurement'
  - How many participants do we need?
  - How long do we need to run the trial for?
  - Are we collecting the data we need? (And at the right time)?

---

### House price index

<iframe src="HPI.html" width=960 height=720></iframe>

</section>

---

<section>

## And finally...

---

### What skills do you need to develop?

- Communication
- Programming (multiple languages)
- A critical eye

</section>
